### ISSUE TITLE
[Cocom] Analysis fail with some repositories

### ISSUE THREAD

**Issue by florentk** [kiwix/metrics#16]
I got this error :
```
2019-12-31 17:40:08 > 2019-12-31 16:40:05,843 - grimoire_elk.elk - ERROR - Error enriching ocean from cocom (https://github.com/kiwix/tools): 'message'
2019-12-31 17:40:08 > Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 672, in enrich_backend
    enrich_count = enrich_items(ocean_backend, enrich_backend)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 452, in enrich_items
    total = enrich_backend.enrich_items(ocean_backend)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/enriched/cocom.py", line 223, in enrich_items
    rich_items = self.get_rich_items(item)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/enriched/cocom.py", line 183, in get_rich_items
    eitem['message'] = entry['message']
2019-12-31 17:40:08 > KeyError: 'message'
```
with theses repository :
- https://github.com/kiwix/web
- https://github.com/kiwix/tools
- https://github.com/kiwix/kiwix-tools
- https://github.com/kiwix/kiwix-lib
- https://github.com/kiwix/apple

**Comment by florentk** [comment]
fix via https://github.com/florentk/grimoirelab-elk/commit/1f79b5f165086bab066ffb88f7cc3d8fe2f084f0
